"""add llm_models table

Revision ID: 35275979bf12
Revises: d21fdff36b0d
Create Date: 2026-03-23 23:25:41.558983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35275979bf12'
down_revision: Union[str, Sequence[str], None] = 'd21fdff36b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_models',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('host', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_models_host'), ['host'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_models_host'))

    op.drop_table('llm_models')
    # ### end Alembic commands ###
