"""add economic_events table

Revision ID: 3ffaf8f034eb
Revises: 6302d4752f03
Create Date: 2026-04-07 23:46:34.972427

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ffaf8f034eb"
down_revision: str | Sequence[str] | None = "6302d4752f03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economic_events",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("event_key", sa.String(length=100), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=3), nullable=False),
        sa.Column("country_name", sa.String(length=50), nullable=False),
        sa.Column("institution", sa.String(length=80), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("importance", sa.String(length=10), nullable=False),
        sa.Column("expected", sa.String(length=30), nullable=False),
        sa.Column("actual", sa.String(length=30), nullable=False),
        sa.Column("previous", sa.String(length=30), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("indicator_key", sa.String(length=30), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_key", name="uq_economic_event_key"),
    )
    with op.batch_alter_table("economic_events", schema=None) as batch_op:
        batch_op.create_index("ix_economic_events_category", ["category"], unique=False)
        batch_op.create_index("ix_economic_events_country", ["country"], unique=False)
        batch_op.create_index("ix_economic_events_date", ["date"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("economic_events", schema=None) as batch_op:
        batch_op.drop_index("ix_economic_events_date")
        batch_op.drop_index("ix_economic_events_country")
        batch_op.drop_index("ix_economic_events_category")

    op.drop_table("economic_events")
    # ### end Alembic commands ###
