"""initial schema

Revision ID: 4ad0174a6de3
Revises: 
Create Date: 2026-03-20 01:34:43.628200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad0174a6de3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('report_id', sa.String(length=16), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_ticker'), 'alerts', ['ticker'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('alert_price', sa.Float(), nullable=False),
    sa.Column('alert_change_pct', sa.Float(), nullable=False),
    sa.Column('alert_volume', sa.Integer(), nullable=False),
    sa.Column('final_recommendation', sa.String(length=20), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('final_confidence', sa.Float(), nullable=False),
    sa.Column('fraud_risk_level', sa.String(length=10), nullable=False),
    sa.Column('fraud_risk_score', sa.Float(), nullable=False),
    sa.Column('fraud_flags', sa.Text(), nullable=False),
    sa.Column('reddit_mentions', sa.Integer(), nullable=False),
    sa.Column('stocktwits_bullish', sa.Integer(), nullable=False),
    sa.Column('stocktwits_bearish', sa.Integer(), nullable=False),
    sa.Column('insider_buys', sa.Integer(), nullable=False),
    sa.Column('insider_sells', sa.Integer(), nullable=False),
    sa.Column('news_count', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('user_action', sa.String(length=10), nullable=False),
    sa.Column('trade_id', sa.String(length=16), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_generated_at'), 'reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_reports_ticker'), 'reports', ['ticker'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('telegram_messages',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('chat_id', sa.String(length=30), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('report_id', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_messages_ticker'), 'telegram_messages', ['ticker'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=12), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('broker_order_id', sa.String(length=50), nullable=False),
    sa.Column('report_id', sa.String(length=16), nullable=False),
    sa.Column('is_closing_trade', sa.Boolean(), nullable=False),
    sa.Column('realised_pnl', sa.Float(), nullable=True),
    sa.Column('realised_pnl_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_executed_at'), 'trades', ['executed_at'], unique=False)
    op.create_index(op.f('ix_trades_report_id'), 'trades', ['report_id'], unique=False)
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    op.create_table('universe',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('t212_ticker', sa.String(length=30), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('avg_volume', sa.Integer(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('in_universe', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_universe_in_universe'), 'universe', ['in_universe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_universe_in_universe'), table_name='universe')
    op.drop_table('universe')
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_report_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_executed_at'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_telegram_messages_ticker'), table_name='telegram_messages')
    op.drop_table('telegram_messages')
    op.drop_table('settings')
    op.drop_index(op.f('ix_reports_ticker'), table_name='reports')
    op.drop_index(op.f('ix_reports_generated_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_ticker'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
