"""add policy_rates table

Revision ID: d21fdff36b0d
Revises: 638434f7e199
Create Date: 2026-03-23 17:56:35.719979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21fdff36b0d'
down_revision: Union[str, Sequence[str], None] = '638434f7e199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_rates',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('central_bank', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', name='uq_policy_rate_country')
    )
    with op.batch_alter_table('policy_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_rates_country_code'), ['country_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_rates_country_code'))

    op.drop_table('policy_rates')
    # ### end Alembic commands ###
