"""add screener_alert_log table

Revision ID: dad13af2f6e6
Revises: 894bda2d0718
Create Date: 2026-03-23 12:19:15.217532

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dad13af2f6e6"
down_revision: str | Sequence[str] | None = "894bda2d0718"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screener_alert_log",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("screener_id", sa.String(length=16), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("change_pct", sa.Float(), nullable=True),
        sa.Column("alert_data_json", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["screener_id"], ["saved_screeners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("screener_alert_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_screener_alert_log_screener_id"), ["screener_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_screener_alert_log_ticker"), ["ticker"], unique=False)
        batch_op.create_index(
            "ix_screener_alert_screener_date", ["screener_id", "sent_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("screener_alert_log", schema=None) as batch_op:
        batch_op.drop_index("ix_screener_alert_screener_date")
        batch_op.drop_index(batch_op.f("ix_screener_alert_log_ticker"))
        batch_op.drop_index(batch_op.f("ix_screener_alert_log_screener_id"))

    op.drop_table("screener_alert_log")
    # ### end Alembic commands ###
