"""add cusip_ticker_map and portfolio group column

Revision ID: e59847b8d10a
Revises: ed2e34edf81b
Create Date: 2026-03-22 00:25:40.728741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59847b8d10a'
down_revision: Union[str, Sequence[str], None] = 'ed2e34edf81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cusip_ticker_map',
    sa.Column('cusip', sa.String(length=12), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cusip')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_column('group')

    op.drop_table('cusip_ticker_map')
    # ### end Alembic commands ###
