"""initial schema

Revision ID: ed2e34edf81b
Revises:
Create Date: 2026-03-21 14:46:54.744450

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed2e34edf81b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("change_pct", sa.Float(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("report_id", sa.String(length=16), nullable=True),
        sa.Column("triggered_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_ticker"), ["ticker"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_triggered_at"), ["triggered_at"], unique=False)

    op.create_table(
        "breadth_snapshots",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("advancing", sa.Integer(), nullable=False),
        sa.Column("declining", sa.Integer(), nullable=False),
        sa.Column("unchanged", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("ad_ratio", sa.Float(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("breadth_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_breadth_snapshots_date"), ["date"], unique=False)

    op.create_table(
        "monitored_assets",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("monitored_assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_monitored_assets_ticker"), ["ticker"], unique=True)

    op.create_table(
        "news_sources",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("homepage", sa.String(length=500), nullable=False),
        sa.Column("feeds", sa.Text(), nullable=False),
        sa.Column("group", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "news_stories",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("headline", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "portfolio_holdings",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("portfolio_id", sa.String(length=16), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("portfolio_holdings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_portfolio_holdings_portfolio_id"), ["portfolio_id"], unique=False
        )

    op.create_table(
        "portfolios",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "price_alerts",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("target_price", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("triggered", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("price_alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_price_alerts_ticker"), ["ticker"], unique=False)

    op.create_table(
        "reports",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=12), nullable=False),
        sa.Column("alert_price", sa.Float(), nullable=False),
        sa.Column("alert_change_pct", sa.Float(), nullable=False),
        sa.Column("alert_volume", sa.Integer(), nullable=False),
        sa.Column("final_recommendation", sa.String(length=20), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("final_confidence", sa.Float(), nullable=False),
        sa.Column("fraud_risk_level", sa.String(length=10), nullable=False),
        sa.Column("fraud_risk_score", sa.Float(), nullable=False),
        sa.Column("fraud_flags", sa.Text(), nullable=False),
        sa.Column("reddit_mentions", sa.Integer(), nullable=False),
        sa.Column("stocktwits_bullish", sa.Integer(), nullable=False),
        sa.Column("stocktwits_bearish", sa.Integer(), nullable=False),
        sa.Column("insider_buys", sa.Integer(), nullable=False),
        sa.Column("insider_sells", sa.Integer(), nullable=False),
        sa.Column("news_count", sa.Integer(), nullable=False),
        sa.Column("report_json", sa.Text(), nullable=False),
        sa.Column("user_action", sa.String(length=10), nullable=False),
        sa.Column("trade_id", sa.String(length=16), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_generated_at"), ["generated_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_reports_ticker"), ["ticker"], unique=False)

    op.create_table(
        "risk_free_rates",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("benchmark", sa.String(length=20), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("risk_free_rates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_risk_free_rates_currency"), ["currency"], unique=False)
        batch_op.create_index(batch_op.f("ix_risk_free_rates_date"), ["date"], unique=False)

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "telegram_messages",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("chat_id", sa.String(length=30), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("message_type", sa.String(length=20), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("report_id", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("telegram_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_telegram_messages_ticker"), ["ticker"], unique=False)

    op.create_table(
        "trades",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("order_type", sa.String(length=12), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("total_value", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("broker_order_id", sa.String(length=50), nullable=False),
        sa.Column("report_id", sa.String(length=16), nullable=False),
        sa.Column("is_closing_trade", sa.Boolean(), nullable=False),
        sa.Column("realised_pnl", sa.Float(), nullable=True),
        sa.Column("realised_pnl_pct", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trades_executed_at"), ["executed_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_trades_report_id"), ["report_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trades_ticker"), ["ticker"], unique=False)

    op.create_table(
        "universe",
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("exchange", sa.String(length=20), nullable=False),
        sa.Column("t212_ticker", sa.String(length=30), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=False),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("shares_outstanding", sa.Integer(), nullable=True),
        sa.Column("inferred_market_cap", sa.Float(), nullable=True),
        sa.Column("avg_volume", sa.Integer(), nullable=False),
        sa.Column("last_price", sa.Float(), nullable=False),
        sa.Column("in_universe", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ticker"),
    )
    with op.batch_alter_table("universe", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_universe_in_universe"), ["in_universe"], unique=False)

    op.create_table(
        "watchlist",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("watchlist", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watchlist_ticker"), ["ticker"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("watchlist", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watchlist_ticker"))

    op.drop_table("watchlist")
    with op.batch_alter_table("universe", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_universe_in_universe"))

    op.drop_table("universe")
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trades_ticker"))
        batch_op.drop_index(batch_op.f("ix_trades_report_id"))
        batch_op.drop_index(batch_op.f("ix_trades_executed_at"))

    op.drop_table("trades")
    with op.batch_alter_table("telegram_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_telegram_messages_ticker"))

    op.drop_table("telegram_messages")
    op.drop_table("settings")
    with op.batch_alter_table("risk_free_rates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_free_rates_date"))
        batch_op.drop_index(batch_op.f("ix_risk_free_rates_currency"))

    op.drop_table("risk_free_rates")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_ticker"))
        batch_op.drop_index(batch_op.f("ix_reports_generated_at"))

    op.drop_table("reports")
    with op.batch_alter_table("price_alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_alerts_ticker"))

    op.drop_table("price_alerts")
    op.drop_table("portfolios")
    with op.batch_alter_table("portfolio_holdings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_portfolio_holdings_portfolio_id"))

    op.drop_table("portfolio_holdings")
    op.drop_table("news_stories")
    op.drop_table("news_sources")
    with op.batch_alter_table("monitored_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monitored_assets_ticker"))

    op.drop_table("monitored_assets")
    with op.batch_alter_table("breadth_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_breadth_snapshots_date"))

    op.drop_table("breadth_snapshots")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_triggered_at"))
        batch_op.drop_index(batch_op.f("ix_alerts_ticker"))

    op.drop_table("alerts")
    # ### end Alembic commands ###
